Repository nftables-rs/nftables-rs, pull requests merged in 2025-01, with the labels that each got.

#121 ci: fix uidmap blocked by ubuntu 24.04
  .github/workflows/rust.yml
Labels: bug

#115 feat(helper)!: add apply_and_return_ruleset* helpers
  src/helper.rs
Labels: enhancement

#76 Add documentation for Expressions
  src/expr.rs
  src/lib.rs
Labels: documentation, enhancement

#129 Update LICENSE-MIT copyright owner
  LICENSE-MIT
Labels: documentation
